apiVersion: v1
kind: ConfigMap
metadata:
  name: frigate
  labels:
    app.kubernetes.io/name: frigate
    app.kubernetes.io/instance: frigate
data:
  config.yml: |
    mqtt:
        host: mosquitto.mqtt.svc.cluster.local
    detectors:
      coral:
        type: edgetpu
        device: usb
    go2rtc:
      streams:
        front:
          - rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@1C016A7PAU00072.iot.zelic.io/cam/realmonitor?channel=1&subtype=0
        front_sub:
          - rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@1C016A7PAU00072.iot.zelic.io/cam/realmonitor?channel=1&subtype=1
        pool:
          - rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@1C00812PAU00924.iot.zelic.io/cam/realmonitor?channel=1&subtype=0
        pool_sub:
          - rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@1C00812PAU00924.iot.zelic.io/cam/realmonitor?channel=1&subtype=1
        side:
          - rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@1C00812PAU00919.iot.zelic.io/cam/realmonitor?channel=1&subtype=0
        side_sub:
          - rtsp://{FRIGATE_RTSP_USERNAME}:{FRIGATE_RTSP_PASSWORD}@1C00812PAU00919.iot.zelic.io/cam/realmonitor?channel=1&subtype=1
    cameras:
      front:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/front
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/front_sub
              roles:
                - detect
        detect:
          enabled: True
      pool:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/pool
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/pool_sub
              roles:
                - detect
        detect:
          enabled: True
      side:
        ffmpeg:
          inputs:
            - path: rtsp://127.0.0.1:8554/side
              roles:
                - record
            - path: rtsp://127.0.0.1:8554/side_sub
              roles:
                - detect
        detect:
          enabled: True
    rtmp:
      enabled: False
    detect:
      enabled: False
    record:
      enabled: True
      retain_days: 30
      events:
        retain:
          default: 30
    ffmpeg:
      hwaccel_args: preset-vaapi