apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate
spec:
  capacity:
    storage: 450Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/cameras
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key:  usb-attachment
          operator: In
          values:
          - coral-tpu