apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media
spec:
  capacity:
    storage: 90Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: frigate-media
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /cameras
    server: proxmox.zelic.io