apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://kube-vip.github.io/helm-charts
      targetRevision: 0.2.2.
      chart: kube-vip-cloud-provider
      helm:
        releaseName: kube-vip-cloud-provider
        valueFiles:
        - $values/applications/kube-vip-cloud-provider/values.yaml
    - repoURL: https://github.com/BojanZelic/home-ops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
