apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/cloudflare/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: zelic-system
  syncPolicy:
    automated:
      prune: true