apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare
  namespace: zelic-system
spec:
  encryptedData:
    TUNNEL_TOKEN: AgA+f3imjQlLX3RQ4o6u5/nsVsPO85cjcD61in4ea90plkbtE2lrVxCsmyGo+o8Dq82lzzK3c41Dd6VaU0pUT5zCBcGtxCQ7x7wwRBYzRtXLqlEang8mYfyVFuKUJOxAh66NJ90zY0UOhq5RBk1WYjfNCwxxMt94NU4srTp5RoFu5zGIGPiv3EhNDwBS4DskDMpQsrDpgqOSaWaGgaOLtg4Xn7ZwCoYLG1SlEm8AumXRUKmxQutbwP2AIQKHRUm0QTCgO8e7M+547A8FF5LxXBlmXboG4jEXO8TM+GoNwzrbkWZ8aCeNT9GnFu2WtdyQ3O7sXK/FSjkNaFLjeBNdn2rA2BMkBgy8lDG1LFYBdy863GgtQQsRtFL80jcBbYKzECY+mds0ieP1R3seJ5Tc59ysM7+Ivk2VDGIRJ1c/dXJQ5UzUsAnQTAZoHOyai4IF2MPQUXpjXbMwFNwWmpRYnlEyGFEXwzdEFoyIUMDSuzNqJieWZqACAkfWPZG8FdLmZfK61FEfwXisELxrH/e8Z5wTzPSNASP1ZNLGAr3oC4WWdht2gFaniN1Y+HR69NbTTDFgECX94GcsXrq+eVxJVN9Ycs67OhzH7yBwOVoRx0w0HbnWZ9mg4DZPGIIcqSD+8CanDjQSHD8qEvD10yBUwup6mjOqVoInjds8CwizsQU1bhdeS8+aflCGCNxc1wKV7Eq/k8fCq1HseGzH2SgNO+CxbAUDmJmsqjMrnVkoGYgRozd3593A3EDknkJRq2Vyag0KwXVmadnij1z0GhMxPwGqVMEYr6pz+gFYD85dsGcCzXjH+nZNICFBQYGQ6CvZbWKPs/gDz72yxYc8URRqyCcRnoIZ4zcR+Mpp/I5cpAcnaxI1Tp1z+hEw1z6fGxB7uWO7/VmG+zGXaEyIh4UbgyoMqUO6om1l+YVpGnqjqyQU4gxAYbj4Myvw
  template:
    metadata:
      name: cloudflare
      namespace: zelic-system

