apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://charts.crossplane.io/stable
      targetRevision: 1.12.0
      chart: crossplane
      helm:
        releaseName: crossplane
        valueFiles:
        - $values/applications/crossplane/values.yaml
    - repoURL: https://github.com/BojanZelic/home-ops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/crossplane/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
     prune: true