apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cockroachdb-operator
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/cockroachdb-operator/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: cockroach-operator-system
  syncPolicy: {}