apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: argocd
  namespace: argo-system
spec:
  name: ArgoCD
  domain: argocd.zelic.io
  autoRedirectToIdentity: true
  policies: 
    - name: Allow Home
      decision: allow
      include:
        - accessGroups:
          - valueFrom:
              name: default-cloudflare-accessgroup
              namespace: zero-trust-system