apiVersion: v1
kind: Secret
metadata:
  name: github.com-bojanzelic-home-ops
  namespace: argo-system
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/BojanZelic/home-ops.git