apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  name: Home Assistant
  domain: home-assistant.zelic.io
  policies: 
    - name: Allow Home
      decision: allow
      include:
        - accessGroups:
          - valueFrom:
            name: default-cloudflare-accessgroup
            namespace: zero-trust-system