env:
  TZ: America/Phoenix

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

controller:
  replicas: 0
  
ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations: 
      external-dns.alpha.kubernetes.io/target: 03d39176-e294-4b8a-8895-23b83f7e1063.cfargotunnel.com
    hosts:
    - host: nzbget.internal.zelic.io
      paths:
        - path: /
          pathType: Prefix
    - host: nzbget.zelic.io
      paths:
        - path: /
          pathType: Prefix

persistence:
  config:
    enabled: true
    storageClass: longhorn
    size: 1Gi
  downloads:
    enabled: true
    mountPath: /downloads
    storageClass: nzbget-downloads
    accessMode: ReadWriteMany
    size: 200Gi