# apiVersion: crdb.cockroachlabs.com/v1alpha1
# kind: CrdbCluster
# metadata:
#   name: cockroachdb
# spec:
#   dataStore:
#     pvc:
#       spec:
#         accessModes:
#           - ReadWriteOnce
#         resources:
#           requests:
#             storage: "20Gi"
#         volumeMode: Filesystem
#         storageClassName: local-path
#   resources:
#     requests:
#       # This is intentionally low to make it work on local k3d clusters.
#       cpu: 500m
#       memory: 1Gi
#     limits:
#       memory: 1Gi
#   tlsEnabled: true
#   image:
#     name: cockroachdb/cockroach:v23.1.4
#   # nodes refers to the number of crdb pods that are created
#   # via the statefulset
#   nodes: 3
#   # affinity is a new API field that is behind a feature gate that is
#   # disabled by default.  To enable please see the operator.yaml file.

#   # The affinity field will accept any podSpec affinity rule.
#   affinity:
#     podAntiAffinity:
#        preferredDuringSchedulingIgnoredDuringExecution:
#        - weight: 100
#          podAffinityTerm:
#            labelSelector:
#              matchExpressions:
#              - key: app.kubernetes.io/instance
#                operator: In
#                values:
#                - cockroachdb
#            topologyKey: kubernetes.io/hostname

#   # nodeSelectors used to match against
#   # nodeSelector:
#   #   worker-pool-name: crdb-workers