env:
  TZ: America/Phoenix

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

ingress:
  main:
    enabled: true
    hosts:
    - host: radarr.internal.zelic.io
      paths:
        - path: /
          pathType: Prefix

persistence:
  config:
    enabled: true
    storageClass: longhorn
    accessMode: ReadWriteOnce
    size: 1Gi
  downloads:
    enabled: true
    mountPath: /downloads
    storageClass: nzbget-downloads
    existingClaim: nzbget-downloads
    accessMode: ReadWriteMany
    size: 200Gi
  media:
    enabled: true
    mountPath: /media
    accessMode: ReadWriteMany
    size: 3Ti
    storageClass: movies-storage