# Uncomment this if you would like to have Cilium restart all unmanaged pods when it is installed.
# If not using this option, you will need to manually restart all unmanaged pods as described in:
# https://docs.cilium.io/en/stable/gettingstarted/k8s-install-helm/#restart-unmanaged-pods
#
# nodeinit.restartPods: true

hubble:
  enabled: true
  metrics:
    enabled:
    - 'flow:sourceContext=namespace;destinationContext=namespace'
  listenAddress: ":4244"
  relay:
    enabled: true

agent: true

# Starts Cilium in non-blocking mode, to change see
# https://docs.cilium.io/en/stable/policy/intro/#policy-enforcement-modes
policyEnforcementMode: "never"

# Monitors for packet drops
monitor:
  enabled: true
  eventTypes: ["drop", "policy-verdict"]

# Required when deploying Cilium to a namespace besides kube-system
# https://github.com/cilium/cilium/pull/13878
resourceQuotas:
  enabled: true
