repositories:
- name: stable
  url: https://charts.helm.sh/stable

releases:
- name: prometheus
  namespace: gitlab-managed-apps
  chart: stable/prometheus
  version: 10.4.1
  installed: true
  values:
    - values.yaml
