apiVersion: v1
kind: PersistentVolume
metadata:
  name: personal-videos
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: personal-videos
  nfs:
    path: /NAS/personal_media/videos
    server: proxmox.zelic.io