apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sbfspot
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/sbfspot/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sbfspot
  syncPolicy:
    automated:
      prune: true
