apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argo-system
spec:
  project: home-ops
  source:
    chart: cert-manager
    helm:
      parameters:
        - name: installCRDs
          value: "true"
    repoURL: https://charts.jetstack.io
    targetRevision: v1.7.1
  destination:
  destination:
    server: https://kubernetes.default.svc
    namespace: gitlab-managed-apps
  syncPolicy: {}
    #automated:
     # prune: true