apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: nodejs-poolcontroller
  namespace: home-assistant
spec:
  name: NodeJS PoolController
  domain: nodejs-poolcontroller.zelic.io
  autoRedirectToIdentity: true
  policies: 
    - name: Allow Home
      decision: allow
      include:
        - accessGroups:
          - valueFrom:
              name: default-cloudflare-accessgroup
              namespace: zero-trust-system