---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-poolcontroller-dashpanel
spec:
  selector:
    matchLabels:
      app: nodejs-poolcontroller-dashpanel
  template:
    metadata:
      labels:
        app: nodejs-poolcontroller-dashpanel
    spec:
      replicas: 1
      containers:
        - image: ghcr.io/bojanzelic/nodejs-poolcontroller-dashpanel:sha-804ddc1055b6405271c3516bcb0d6842c3519d88
          name: nodejs-poolcontroller-dashpanel
          ports:
            - containerPort: 5150
          # volumeMounts:
          # - name: config
          #   mountPath: /app/config.json
      volumes:
      - name: config
        configMap:
          name: poolcontroller-config
          items:
          - key: config.json
            path: config.json