---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-poolcontroller
spec:
  selector:
    matchLabels:
      app: nodejs-poolcontroller
  template:
    metadata:
      labels:
        app: nodejs-poolcontroller
    spec:
      containers:
        - image: ghcr.io/bojanzelic/nodejs-poolcontroller:latest
          name: nodejs-poolcontroller
          ports:
            - containerPort: 4200
          volumeMounts:
          - name: config
            mountPath: /app/config.json
            subPath: config.json
          env:
            - name: TZ
              value: America/Phoenix
      volumes:
      - name: config
        configMap:
          name: poolcontroller-config