apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - secret.yaml
  - github.com/kubernetes-sigs/external-dns/kustomize
  - cloudflare-internal.yaml

namespace: dns-system

patchesStrategicMerge:
  - cloudflare.yaml

images:
  - name: registry.k8s.io/external-dns/external-dns
    newTag: v0.13.1