apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns.yaml
  - secret.yaml
  - github.com/kubernetes-sigs/external-dns/kustomize

namespace: dns-system

patchesStrategicMerge:
  - cloudflare.yaml