apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 5.51.6
      chart: argo-cd
      helm:
        releaseName: argo
        valueFiles:
        - $values/applications/argocd/values.yaml
    - repoURL: https://github.com/BojanZelic/home-ops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/argocd/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-system
  syncPolicy:
    automated:
      prune: true