podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    storageClass: longhorn
    size: 1Gi

  tv:
    enabled: true
    storageClass: tv-storage
    existingClaim: sonarr-tv
    accessMode: ReadWriteMany
    size: 2Ti
    
  movies:
    enabled: true
    mountPath: /media
    existingClaim: radarr-media
    accessMode: ReadWriteMany
    size: 3Ti
    storageClass: movies-storage

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    hosts:
    - host: bazarr.internal.zelic.io
      paths:
        - path: /
          pathType: Prefix