apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metal-lb
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/metal-lb/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb-system
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: certificaterequests.cert-manager.io
    jsonPointers:
      - /status
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: addresspools.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
