apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv-storage
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tv-storage
  nfs:
    path: /NAS/media/tv
    server: proxmox.zelic.io