apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: nzbget
  namespace: media-services
spec:
  name: Nzbget
  domain: nzbget.zelic.io
  autoRedirectToIdentity: true
  policies: 
    - name: Allow Home
      decision: allow
      include:
        - accessGroups:
          - valueFrom:
              name: default-cloudflare-accessgroup
              namespace: zero-trust-system