apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mqtt
resources:
  - namespace.yaml
  - service.yaml
  - service-p.yaml
  - deployment.yaml
  - deployment-b.yaml


configMapGenerator:
  - name: bridge-conf
    files:
      - config/mosquitto.conf
