---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-lb
  namespace: mqtt
spec:
  type: LoadBalancer
  ports:
    - name: mqtt
      port: 1883
      targetPort: 1883
    - name: wss
      port: 9001
      targetPort: 9001
  selector:
    app: mosquitto