apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: samba-system

resources:
  - https://github.com/samba-in-kubernetes/samba-operator//config/default?ref=v0.4

patches:
  # https://github.com/samba-in-kubernetes/samba-operator/issues/324
- path: patch_node_affinity.yaml
  target:
    kind: Deployment