apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zero-trust-system
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/zero-trust-system/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: zero-trust-system
  syncPolicy:
    automated:
      prune: true