apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://charts.gabe565.com
      targetRevision: 0.10.0
      chart: paperless-ngx
      helm:
        releaseName: paperless-ngx
        valueFiles:
        - $values/applications/paperless/values.yaml
    - repoURL: https://github.com/BojanZelic/home-ops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/paperless/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: paperless
  ignoreDifferences:
  - group: ""
    jsonPointers:
    - /data/redis-password
    kind: Secret
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      prune: true