repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
- name: paperless
  namespace: paperless
  version: 8.6.1
  chart: k8s-at-home/paperless
  installed: true
  values:
    - values.yaml
