
image:
  # -- Image repository
  repository: ghcr.io/paperless-ngx/paperless-ngx
  # -- Image pull policy
  pullPolicy: IfNotPresent
  # -- Image tag
  tag: 1.17.4

# -- Environment variables [[ref]](https://docs.paperless-ngx.com/configuration/)
# @default -- See [values.yaml](./values.yaml)
env:
  # -- Set the container timezone
  TZ: UTC
  # PAPERLESS_SECRET_KEY: ""

service:
  # -- Configures service settings for the chart.
  # @default -- See [values.yaml](./values.yaml)
  main:
    ports:
      http:
        port: 8000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  main:
    enabled: true
    annotations:
      external-dns.alpha.kubernetes.io/target: 03d39176-e294-4b8a-8895-23b83f7e1063.cfargotunnel.com
    hosts:
      - host: paperless-ngx.zelic.io
        paths:
          - path: /
            pathType: Prefix
    # tls:
    #   - secretName: chart-example.local
    #     hosts:
    #       - chart-example.local

initContainers:
  init-litestream:
    name: init-litestream
    image: litestream/litestream:0.3
    args: ['restore', '-if-db-not-exists', '-if-replica-exists', '/usr/src/paperless/data/db.sqlite3']
    volumeMounts:
    - name: data
      mountPath: /usr/src/paperless/data
    - name: litestream
      mountPath: /etc/litestream.yml
      subPath: litestream.yml
    env:
    - name: LITESTREAM_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: lightstream-s3
          key: LITESTREAM_ACCESS_KEY_ID
    - name: LITESTREAM_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: lightstream-s3
          key: LITESTREAM_SECRET_ACCESS_KEY

configMaps:
  litestream:
    enabled: true
    # -- Homer configuration. [[ref]](https://github.com/bastienwirtz/homer/blob/main/docs/configuration.md)
    # @default -- See [values.yaml](./values.yaml)
    data:
      litestream.yml: |-
        dbs:
        - path: /usr/src/paperless/data/db.sqlite3
          replicas:
            - url: s3://zelic-io-paperless/db.sqlite3
sidecars:
  ligtestream: 
    name: litestream
    image: litestream/litestream:0.3
    args: ['replicate']
    volumeMounts:
    - name: data
      mountPath: /usr/src/paperless/data
    - name: litestream
      mountPath: /etc/litestream.yml
      subPath: litestream.yml
    env:
    - name: LITESTREAM_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: lightstream-s3
          key: LITESTREAM_ACCESS_KEY_ID
    - name: LITESTREAM_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: lightstream-s3
          key: LITESTREAM_SECRET_ACCESS_KEY
    ports:
    - name: metrics
      containerPort: 9090

persistence:
  litestream:
    enabled: true
    type: configMap
    name: paperless-ngx-litestream
  # -- Configure data volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  data:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/data
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 1Gi
  # -- Configure media volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  media:
    enabled: false
    retain: true
    mountPath: /usr/src/paperless/media
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 8Gi
  # -- Configure export volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  export:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/export
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 1Gi
  # -- Configure consume volume settings for the chart under this key.
  # @default -- See [values.yaml](./values.yaml)
  consume:
    enabled: true
    retain: true
    mountPath: /usr/src/paperless/consume
    storageClass: "longhorn"
    accessMode: ReadWriteOnce
    size: 1Gi

# -- Enable and configure redis subchart under this key.
#    If enabled, the app's Redis env will be set for you.
#    [[ref]](https://github.com/bitnami/charts/tree/main/bitnami/redis)
# @default -- See [values.yaml](./values.yaml)
redis:
  enabled: true
  auth:
    enabled: true
  master:
    persistence:
      enabled: false
  replica:
    replicaCount: 0