apiVersion: samba-operator.samba.org/v1alpha1
kind: SmbShare
metadata:
  name: paperless-smb
spec:
  commonConfig: samba-config
  storage:
    pvc:
      name: "paperless-ngx-consume"
  readOnly: false
