repositories:
  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/

releases:
- name: plex
  namespace: media-services
  version: 6.4.3
  chart: k8s-at-home/plex
  installed: true
  values:
    - values.yaml

# - name: plex-manifests
#   namespace: media-services
#   chart: incubator
#   values: 
#    - /Users/bojanzelic/Projects/zelic.io-k8s-pi/applications/plex/manifests/pv.yml