repositories:
  - name: longhorn
    url: https://charts.longhorn.io

releases:
- name: longhorn
  namespace: longhorn-system
  chart: longhorn/longhorn
  version: 1.3.2
  installed: true
  values:
    - values.yaml
