apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies-storage
spec:
  capacity:
    storage: 3Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: movies-storage
  nfs:
    path: /NAS/media/movies
    server: proxmox.zelic.io