apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/frigate/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy: {}