apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frigate
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://blakeblackshear.github.io/blakeshome-charts/
      targetRevision: 7.0.0
      chart: frigate
      helm:
        releaseName: frigate
        valueFiles:
        - $values/applications/frigate/values.yaml
    - repoURL: https://github.com/BojanZelic/home-ops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/frigate/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true