apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: frigate-creds
  namespace: home-assistant
spec:
  encryptedData:
    FRIGATE_RTSP_PASSWORD: AgCjknwK+dT5ljf2S0N2t3AVYiy+QwpdWnWckiJjGK3bz8FmdGsuutH3KWGFjk7YePXXRk8efnzCFL777QM53f+67qmT8IuEYoPrUyAutKJ7/oSsek/PvOuRPrlj6B0WcpC9YXiA0FW6aEMNWXnO6R40TJ2F5fMstUQWIZQQkQTHCFY2Z36lQIW/RF9GzkbL0PBHeTijS/z2MQ8cWp+HZuTn6ebvFH6WY3F+wm0XrFG2sDwRTnWQYS/oMZBXohDw2pZ1r4tY0gR7504Pnv5xS5bSt4fCzFs/jvdAmseonxoe/CQtd0IFxkk7tITMA2LqR/d+BvDCvCBO8lr81LVFbBaakX+yxc4aHZQc4pmWXtXT67K9mjWzrpheUK+IK71uRkZf2R6ek2Whi78UWxX+I8AKTB4tc+To7CrZogFTWgyd/u732tjVAPFMqlFV2eiFIXKChMmmiLPBMCpsiV/vasVp9M/b1BiUjPigPJvRinzJuHtKbUdkcN8hZwlxKeHLLOo0IZ2rXnZfiuV/czqTUNPxTFqNJo7YBOIYOBCrXO8yom6Ms4Y28YPbhmZ14AlkQ4feGfgfUXOgXZ4yAh2I1TrCz8dbcirNZLf9yiunk0v4sI7sXfIOAB+DX/ukEU7F3XEcZwkyE0xRIlCx/C0VpjEyz7uej2jz4hjJLkQWVl5ga1tEq+Jsp/wwycU6FOjRBB7W9TnVMg==
    FRIGATE_RTSP_USERNAME: AgCJvsDbmeOdtHp+JEbW1v8Z7bq8ulE+pA2gPPR2VeyJnsuw0nwi4hdJnB8rpcpQo8JNomvfAFyhhjN//xQmi0O0HI+yhXfhQtlRiKfPZhJLYoLkqtHwJ2ZhfVMwfXa0qJrM4PuyjpYD3t2jxyV5OQhbtxsVpKT40Marb4OlGBzPL9OOFj9brjw5xkIlDvj+17jKmCshftmGPAvcDFDJIkEUabUDAYDCVpTQfvEtDxty+33iic5wlbBcTJMxuoEz6LPBgukYcP/gecW0xJ9k27yPIMT/pPN/n2oyuJKnuUN74fXN2Yz/XBJxw/vioDmWtxnGCwIpw4Wxb00kqoVN6UkRme0dbUeFADNzKm9jhAoOGqmODdl8eHUZZmK0w/D9Pd2TV6crB5IZTxxrJX64RNFckNplKT9zyZ6CGiI9O6p+tSRCQbQBxFDUFQUGAV9w61QJXlKXXH0ncnGNMQjvxglSkFMljR8dK3I91zUXUyUDOmUdTo0gQeTvD2zdS92/mUNjfa7BIcZY9Cl4CpIMzuL8NsgcsJM4hd3WuaoKmbQaYUYxzbW86ZBLCeHyGlTABiVFO8Giy0Iqt5E++8JEUErIsUyzR5aoGHognAbB5oey4gY7c2es/XK3ZR7OoTbwN4pJUnTbwM/UbzqdwzIOYV2PyTEpA/3CWJlJdkfsxCOQ8UlymqPIKpk/mmccLvoHRE/fnujtGg==
  template:
    metadata:
      name: frigate-creds
      namespace: home-assistant

