apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - nameReference.yaml

namespace: zero-trust-system

resources:
  - https://github.com/BojanZelic/cloudflare-zero-trust-operator//config/default?ref=prefer-api-token-over-email
  - secret.yaml