apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: http://pajikos.github.io/home-assistant-helm-chart/
      targetRevision: 0.2.92
      chart: home-assistant
      helm:
        releaseName: home-assistant
        valueFiles:
        - $values/applications/home-assistant/values.yaml
    - repoURL: https://github.com/BojanZelic/home-ops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/home-assistant/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
