# podSecurityContext:
#   runAsUser: 1000
#   runAsGroup: 1000
#   fsGroup: 1000
image:
  repository: homeassistant/home-assistant
  tag: 2023.12.0

env:
  # -- Set the container timezone
  TZ: UTC

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    accessMode: ReadWriteOnce
    storageClass: longhorn
    size: 1Gi

hostNetwork: true

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    annotations: 
      external-dns.alpha.kubernetes.io/target: 03d39176-e294-4b8a-8895-23b83f7e1063.cfargotunnel.com
    hosts:
    - host: homeassistant.internal.zelic.io
      paths:
        - path: /
          pathType: Prefix
    - host: home-assistant.zelic.io
      paths:
        - path: /
          pathType: Prefix