apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zwave-js
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://charts.ar80.eu
      targetRevision: 0.2.116
      chart: zwave-js-ui
      helm:
        releaseName: zwave-js-ui
        valueFiles:
        - $values/applications/zwave-js/values.yaml
    - repoURL: https://github.com/BojanZelic/home-ops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/BojanZelic/home-ops.git
      path: applications/zwave-js/manifests
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: home-assistant
  syncPolicy:
    automated:
      prune: true
