# Default values for zwave-js-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: zwavejs/zwave-js-ui
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# -- configure Probes
health:
  livenessProbe:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 30
    httpHeaders:
    - name: Accept
      value: "text/plain"
  readinessProbe:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 30
    httpHeaders:
    - name: Accept
      value: "text/plain"
  startupProbe:
    path: /health
    initialDelaySeconds: 5
    periodSeconds: 30
    httpHeaders:
    - name: Accept
      value: "text/plain"

# -- ui and websocet ports
ports:
  ui:
    name: http-ui
    containerPort: 8091
    servicePort: 80
    protocol: TCP
  websocket:
    name: http-websocket
    containerPort: 3000
    servicePort: 3000
    protocol: TCP

service:
  type: ClusterIP
  port: 8091  
  annotations: {}

# -- Setting default strategy, to avoid running 2 containers with one stick
strategy:
  type: Recreate

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- add your env variables here, following standard syntax
env:
  - name: ZWAVE_JS_EXTERNAL_CONFIG
    value: /usr/src/app/store/.config-db

# -- you can add secrets and configmaps. this way you support external secrets for secure variables
envFrom: []

podAnnotations: {}

podSecurityContext:
  privilaged: true

  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

persistence:
  # -- enable persistent volume, otherwise use empty dir
  enabled: true
  storageClass: longhorn
  size: 1Gi
  accessMode: ReadWriteOnce
  # existingClaim: my-claim
  # -- change the path of store. Just in case you use different env variable.
  mountPath: /usr/src/app/store
  # -- Optionally specify a subPath
  # subPath: /path/to/config

# -- Support custom usb device
usbDevice: /dev/serial/by-id/usb-Zooz_800_Z-Wave_Stick_533D004242-if00

ingress:
  enabled: true
  annotations: 
    external-dns.alpha.kubernetes.io/target: 03d39176-e294-4b8a-8895-23b83f7e1063.cfargotunnel.com
  hosts:
  - host: zwave-js.internal.zelic.io
    paths:
      - path: /
        pathType: Prefix
  - host: zwave-js.zelic.io
    paths:
      - path: /
        pathType: Prefix
  tls: []

resources:
  requests:
    memory: 192Mi

nodeSelector:
  zwave-usb: "true"

tolerations: []

affinity: {}