apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argo-system
spec:
  project: home-ops
  sources:
    - repoURL: https://bitnami-labs.github.io/sealed-secrets/
      targetRevision: 2.7.2
      chart: sealed-secrets
      helm:
        releaseName: sealed-secrets
        valueFiles:
        - $values/applications/sealed-secrets/values.yaml
    - repoURL: https://github.com/BojanZelic/home-ops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  syncPolicy:
    automated:
      prune: true
